export const ADDITION = "ADDITION_ACTION";
export const SUBSTRACTION = "SUBSTRACTION_ACTION";
export const UPDATENUMBER = "UPDATE_NUMBER_ACTION";
export const UPDATEOPERATOR = "UPDATE_OPERATOR_ACTION";

export const CLEARALL = "CLEAR_ALL_ACTION";

export const UPDATEDISPLAY = "UPDATE_DISPLAY_ACTION";
